version: "3"

services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - custom_network
    container_name: app_api

  client:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - custom_network
    container_name: app_client

  admin:
    build: ./admin
    ports:
      - "4001:4001"
    depends_on:
      - db
    networks:
      - custom_network
    container_name: app_admin

  db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongovol:/data/db
    networks:
      - custom_network
    container_name: app_db

volumes:
  mongovol:
networks:
  custom_network:
